
services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "5000:80"
    volumes:
      - ./keys:/keys

  backend:
    build:
      context: ./Backend
    ports:
      - "5001:80"
